export const PRIZE_PRODUCTS_DATASOURCE_REQUEST = 'APP/PRIZE_PRODUCTS_DATASOURCE_REQUEST';
export const PRIZE_PRODUCTS_DATASOURCE_FAILURE = 'APP/PRIZE_PRODUCTS_DATASOURCE_FAILURE';
export const PRIZE_PRODUCTS_DATASOURCE_SUCCESS = 'APP/PRIZE_PRODUCTS_DATASOURCE_SUCCESS';
