export const SUBJECT_DATASOURCE_REQUEST = 'APP/SUBJECT_DATASOURCE_REQUEST';
export const SUBJECT_DATASOURCE_FAILURE = 'APP/SUBJECT_DATASOURCE_FAILURE';
export const SUBJECT_DATASOURCE_SUCCESS = 'APP/SUBJECT_DATASOURCE_SUCCESS';
