export const SERIES_DATASOURCE_REQUEST = 'APP/SERIES_DATASOURCE_REQUEST';
export const SERIES_DATASOURCE_FAILURE = 'APP/SERIES_DATASOURCE_FAILURE';
export const SERIES_DATASOURCE_SUCCESS = 'APP/SERIES_DATASOURCE_SUCCESS';
