export const OUTLINE_DATASOURCE_REQUEST = 'APP/OUTLINE_DATASOURCE_REQUEST';
export const OUTLINE_DATASOURCE_FAILURE = 'APP/OUTLINE_DATASOURCE_FAILURE';
export const OUTLINE_DATASOURCE_SUCCESS = 'APP/OUTLINE_DATASOURCE_SUCCESS';
