export const PRIZE_GOODS_DATASOURCE_REQUEST = 'APP/PRIZE_GOODS_DATASOURCE_REQUEST';
export const PRIZE_GOODS_DATASOURCE_FAILURE = 'APP/PRIZE_GOODS_DATASOURCE_FAILURE';
export const PRIZE_GOODS_DATASOURCE_SUCCESS = 'APP/PRIZE_GOODS_DATASOURCE_SUCCESS';
