export const PRIZE_ACTIVITY_DATASOURCE_REQUEST = 'APP/PRIZE_ACTIVITY_DATASOURCE_REQUEST';
export const PRIZE_ACTIVITY_DATASOURCE_FAILURE = 'APP/PRIZE_ACTIVITY_DATASOURCE_FAILURE';
export const PRIZE_ACTIVITY_DATASOURCE_SUCCESS = 'APP/PRIZE_ACTIVITY_DATASOURCE_SUCCESS';
